### ISSUE TITLE
Are reported XSS issues still present in 3.0.2?

### ISSUE THREAD

**Issue by alehel** [directwebremoting/dwr#14]
I was wondering if the issues reported here: https://www.cvedetails.com/vulnerability-list/vendor_id-14953/product_id-30363/Directwebremoting-Direct-Web-Remoting.html are still present in the latest 3.0.2 version of DWR?

**Comment by mikewse** [comment]
Please do not use the issue tracker for questions.
First search our mailing list archive at http://dwr.2114559.n2.nabble.com/ and then if needed ask questions in our new forum at https://discourse.dojo.io/c/dwr-users.
